version: '3'

services:

  # node_api:
  #   build: .
  #   environment:
  #     - PORT=1337
  #     - ENV_IN=docker
  #   ports:
  #     - "1337:1337"
  #     - "3000:3000"
  #   volumes:
  #     - ./logs:/app/logs
  #   # networks:
  #   #   - db
  #   restart: always
  
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
    # networks:
    #   - db
    environment:
      POSTGRES_USER: HintedAdmin
      POSTGRES_PASSWORD: HintEdQaz
      POSTGRES_DB: HintEd

# networks:
#   db:
#     driver: bridge

volumes:
    postgres_database:
        external: true